name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p $HOME/.ssh/ && touch $HOME/.ssh/known_hosts
          chmod 600 $HOME/.ssh/known_hosts
          ssh-keyscan 34.100.132.156 >> $HOME/.ssh/known_hosts
          echo "${{ secrets.SSH_SECRET_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
      
      - name: Deploy code to VM
        run: |
          ssh -i $HOME/.ssh/id_rsa bruikey03@34.100.132.156 'cd /home/bruikey03/shaunslib && git pull'

