name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh-keyscan 34.100.132.156 >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          chmod 600 ~/.ssh/id_rsa
      
      - name: Deploy code to VM
        run: |
          ssh -i ~/.ssh/id_rsa bruikey03@34.100.132.156 'cd /home/bruikey03/shaunslib && git pull'

