name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy code to VM
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.shh/id_rsa && chmod 600 ~/.ssh/known_hosts
          
          ssh shaun0_03@34.100.132.156 'cd /home/bruikey03/shaunslib && git pull'

