name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
      
      - name: Deploy code to VM
        run: |
          ssh bruikey03@34.100.238.6 'cd /home/bruikey03/shaunslib && git pull'
          

